# kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all resources to
namespace: prd-kuard

resources:
- ../../base

images:
- name: gcr.io/kuar-demo/kuard-amd64
  newName: gcr.io/kuar-demo/kuard-amd64
  newTag: blue

replicas:
- name: kuard
  count: 5