# kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resource config to be applied
resources:
  - supertroopers-deployment.yaml
  - supertroopers-service.yaml
  - namespace.yaml
