apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-alb
  namespace: hello-alb
  labels:
    app: hello-alb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-alb
  template:
    metadata:
      labels:
        app: hello-alb
    spec:
      containers:
      - name: hello-alb
        image: mikealbdemo.azurecr.io/alb/hello-alb:farva
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: acr-secret
