apiVersion: v1
kind: Service
metadata:
  name: hello-alb
  labels:
    app: hello-alb
spec:
  type: LoadBalancer
  selector:
    app: hello-alb
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
