apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-helmrelease
  namespace: cluster-config
spec:
  targetNamespace: monitoring
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: cluster-config
      interval: 1m
  interval: 1m
  install:
    createNamespace: true
